# Generated by Django 6.1 on 2026-08-27 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='onboardingrun',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='runevent',
            name='run',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.RemoveConstraint(
            model_name='organizationfield',
            name='unique_org_field',
        ),
        migrations.RemoveConstraint(
            model_name='workflowstep',
            name='unique_run_step',
        ),
        migrations.DeleteModel(
            name='RunEvent',
        ),
        migrations.RemoveField(
            model_name='organizationfield',
            name='field',
        ),
        migrations.RemoveField(
            model_name='organizationfield',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='run',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationField',
        ),
        migrations.DeleteModel(
            name='OnboardingRun',
        ),
        migrations.DeleteModel(
            name='WorkflowStep',
        ),
    ]
