# Generated by Django 6.1 on 2026-08-28 03:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_organization_fields_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semantic_scholar_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('affiliations', models.JSONField(blank=True, default=list)),
                ('homepage_url', models.URLField(blank=True, max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveSmallIntegerField()),
                ('summary', models.TextField()),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.digest')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semantic_scholar_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('corpus_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=300)),
                ('publication_types', models.JSONField(blank=True, default=list)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('open_access_pdf_url', models.URLField(blank=True, max_length=1000)),
                ('is_open_access', models.BooleanField(default=False)),
                ('citation_count', models.PositiveIntegerField(default=0)),
                ('influential_citation_count', models.PositiveIntegerField(default=0)),
                ('reference_count', models.PositiveIntegerField(default=0)),
                ('fields_of_study', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-publication_date', '-created_at'],
                'indexes': [models.Index(fields=['publication_date'], name='core_paper_publica_8a9544_idx'), models.Index(fields=['publication_year'], name='core_paper_publica_065f0a_idx'), models.Index(fields=['citation_count'], name='core_paper_citatio_4aff6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('relevant', 'Relevant'), ('not_relevant', 'Not relevant'), ('save', 'Save'), ('unsave', 'Unsave'), ('dismiss', 'Dismiss')], max_length=24)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digest_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_events', to='core.digestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_feedback', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_events', to='core.paper')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='digestitem',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paper'),
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_links', to='core.author')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_links', to='core.paper')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='papers',
            field=models.ManyToManyField(related_name='authors', through='core.PaperAuthor', to='core.paper'),
        ),
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expertise_level', models.CharField(choices=[('general', 'General reader'), ('student', 'Student'), ('researcher', 'Researcher'), ('expert', 'Domain expert')], default='general', max_length=20)),
                ('research_focus', models.TextField(blank=True, default='', help_text="Freeform description of the user's research interests/focus, in their own words. Fed directly to the LLM as context when judging paper relevance and ranking")),
                ('summary_style', models.CharField(choices=[('plain', 'Plain language'), ('technical', 'Technical'), ('balanced', 'Balanced')], default='balanced', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('last_paper_check_at', models.DateTimeField(blank=True, help_text="When we last queried Semantic Scholar for new papers for this user. Papers published after this timestamp are considered 'new' on the next check. Null until the first check ever runs.", null=True)),
                ('query_sync_status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=20)),
                ('setup_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('topic', 'Topic'), ('keyword', 'Keyword'), ('author', 'Author'), ('venue', 'Journal or conference'), ('exclude', 'Exclude')], default='topic', max_length=20)),
                ('label', models.CharField(max_length=160)),
                ('query', models.CharField(help_text='Provider search query or normalized matching text.', max_length=500)),
                ('weight', models.DecimalField(decimal_places=3, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weight', 'label'],
            },
        ),
        migrations.CreateModel(
            name='UserPaper',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('saved', 'Saved'), ('dismissed', 'Dismissed')], default='unread', max_length=20)),
                ('latest_relevance_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('source_query', models.CharField(blank=True, max_length=500)),
                ('source_item_id', models.CharField(blank=True, max_length=255)),
                ('latest_rationale', models.TextField(blank=True)),
                ('first_recommended_at', models.DateTimeField(blank=True, null=True)),
                ('last_recommended_at', models.DateTimeField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='core.paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='paperauthor',
            constraint=models.UniqueConstraint(fields=('paper', 'author'), name='unique_paper_author'),
        ),
        migrations.AddConstraint(
            model_name='paperauthor',
            constraint=models.UniqueConstraint(fields=('paper', 'position'), name='unique_paper_position'),
        ),
        migrations.AddConstraint(
            model_name='userinterest',
            constraint=models.UniqueConstraint(fields=('user', 'kind', 'query'), name='unique_user_interest_query'),
        ),
        migrations.AddConstraint(
            model_name='userpaper',
            constraint=models.UniqueConstraint(fields=('user', 'paper'), name='unique_user_paper'),
        ),
    ]
